
/**
Constructor
Do not call Function in Constructor.
*/
class T001()
{
	super();

	//TODO:edit here

}
extends AView;


function T001*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function T001*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function T001*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};

function T001*onAButton1Click(comp, info, e)
{

	    AToast.show('T001 뷰 입니다.'); 

};

