
/**
Constructor
Do not call Function in Constructor.
*/
class T002()
{
	super();

	//TODO:edit here

}
extends AView;


function T002*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function T002*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function T002*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};

function T002*onAButton1Click(comp, info, e)
{

	    AToast.show('T002 뷰 입니다.'); 

};
