
/**
Constructor
Do not call Function in Constructor.
*/
class Tabview2()
{
	super();

	//TODO:edit here

}
extends AView;


function Tabview2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function Tabview2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function Tabview2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
