
/**
Constructor
Do not call Function in Constructor.
*/
class Tabview3()
{
	super();

	//TODO:edit here

}
extends AView;


function Tabview3*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function Tabview3*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function Tabview3*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
