
/**
Constructor
Do not call Function in Constructor.
*/
class InnerView2()
{
	super();

	//TODO:edit here

}
extends AView;


function InnerView2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function InnerView2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function InnerView2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
