
/**
Constructor
Do not call Function in Constructor.
*/
class InnerView0()
{
	super();

	//TODO:edit here

}
extends AView;


function InnerView0*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function InnerView0*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function InnerView0*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
