
/**
Constructor
Do not call Function in Constructor.
*/
class InnerView1()
{
	super();

	//TODO:edit here

}
extends AView;


function InnerView1*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function InnerView1*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function InnerView1*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
